name: Build cosmos-sdk firehose version
run-name: ${{ inputs.dryrun && '[dryrun] ' || ''}}Building p-${{ inputs.tag }}-fh <> cosmos/${{ inputs.tag }}..graphprotocol/${{inputs.fh-tag}}

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'cosmos/cosmos-sdk tag name'
      fh-tag:
        type: string
        required: true
        description: 'graphprotocol/cosmos-sdk firehose tag name'
      dryrun:
        type: boolean
        required: false
        default: false
        description: 'Setting this will only apply commits and run build'

jobs:
  apply-firehose-cosmos-sdk-commits:
    name: Apply firehose/cosmos-sdk's commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/apply-firehose-commits
        with:
          tag: ${{ inputs.tag }}
          fh-tag: ${{ inputs.fh-tag }}
          print-diff: 'y'
      - name: 'Manually do it?'
        if: always() && '!contains(env.TAGS, env.P_TAG)'
        run: |
          STEPS=$(cat << EOF
          => Add remotes
          > git remote add cosmos https://github.com/cosmos/cosmos-sdk.git
          > git remote add gp https://github.com/graphprotocol/cosmos-sdk.git
          
          => Fetch tags
          > git fetch cosmos refs/tags/${{ inputs.tag }}:refs/tags/cosmos_${{ inputs.tag }} --no-tags
          > git fetch gp refs/tags/${{ inputs.fh-tag }}:refs/tags/gp_${{ inputs.fh-tag }} --no-tags
          
          => Check commit diff
          > git log cosmos_${{ inputs.tag }}..gp_${{ inputs.fh-tag }} --pretty='%h | %s [%an]'
          
          => Apply commits
          > git checkout cosmos_${{ inputs.tag }}
          > git cherry-pick \$(git log cosmos_${{ inputs.tag }}..gp_${{ inputs.fh-tag }} --pretty="%H" --reverse | tr '\n' ' ')

          => Test builds
          > LEDGER_ENABLED=false make build

          => Create the tag
          > git tag ${{ env.P_TAG }}
          > git push origin refs/tags/${{ env.P_TAG }}
          EOF
          )
          STEPS="${STEPS//'%'/'%25'}"
          STEPS="${STEPS//$'\n'/'%0A'}"
          STEPS="${STEPS//$'\r'/'%0D'}"
          echo "::notice title=Manually do it?::$STEPS"

  build-firehose-version:
    name: Test build
    needs: apply-firehose-cosmos-sdk-commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/apply-firehose-commits
        with:
          tag: ${{ inputs.tag }}
          fh-tag: ${{ inputs.fh-tag }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - name: 'Test build'
        run: |
          GOARCH=${{ matrix.go-arch }} LEDGER_ENABLED=false make build
  
  create-tag:
    name: Create p-tag
    if: '!inputs.dryrun'
    needs: build-firehose-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/apply-firehose-commits
        with:
          tag: ${{ inputs.tag }}
          fh-tag: ${{ inputs.fh-tag }}
      - name: 'remove .github/workflows dir and create the tag'
        run: |
          rm -rf .github/workflows
          git add -A
          git commit -m "remove .github/workflows dir (to be able to push the tag with default token)"
          git tag ${{ env.P_TAG }}
          git push origin refs/tags/${{ env.P_TAG }}
